### ISSUE TITLE
Strange Bug

### ISSUE THREAD

**Issue by TheKeyblader** [deamme/ts-transform-inferno#10]
Hello 

Thank you for your package, I love it.
But I found a bug
When using ComponentType in Interface Properties

I am using this code to do the bug 

```typescript
import {Component, render, Props, ComponentType } from "inferno";

interface TestProps<T> {
    Template:ComponentType<{Data:T}>
    Data:T
}



class GenericPrinter<T> extends Component<TestProps<T>> {
    constructor(props) {
        super(props);
        this.state={};
    }

    render() {
        let content = <this.props.Template Data={this.props.Data}/>;
        return <div>{content}</div>
    }
}

function Test<T>(props:{Data:T}) {
    return <div>{props.Data.toString()}</div>
}


render(<GenericPrinter Template={Test} Data={"lol"} />,document.body);
```
I obtain this 

```
Error: TypeScript automatic transpilation has failed. Please check that:
            - You have TypeScript installed
            - Your tsconfig.json file is not malformed.
Error message: C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\src\index.tsx: TypeError: Cannot read property 'charAt' of undefined
    at WorkFlowContext.fatal (C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\fuse-box\core\WorkflowContext.js:209:15)
    at File.transpileUsingTypescript (C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\fuse-box\core\File.js:423:26)
    at File.handleTypescript (C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\fuse-box\core\File.js:455:27)
    at File.consume (C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\fuse-box\core\File.js:273:25)
    at ModuleCollection.resolve (C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\fuse-box\core\ModuleCollection.js:185:24)
    at realm_utils_1.each (C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\fuse-box\core\ModuleCollection.js:78:29)
    at iterateMap (C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\realm-utils\dist\commonjs\each.js:43:34)
    at C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\realm-utils\dist\commonjs\each.js:59:17
    at C:\Users\Jean-François\Desktop\Temporaire\Typescript\Generic Inferno\node_modules\realm-utils\dist\commonjs\each.js:63:14
    at new Promise (<anonymous>)
```
on file index.ts line 312
the function "isComponent" is crashing beacause "text" is undefined
when treating the expression

let content = <this.props.Template Data={this.props.Data}/>;

Can you investigate the bug pls ?

Thank you

**Comment by deamme** [comment]
https://github.com/deamme/ts-transform-inferno/commit/b7882411a9d80f6db7c29e6cf56e4be764af83d1 should have fixed it. Let me know if it doesn't

**Comment by TheKeyblader** [comment]
Thank you!!  🎊
